core:
  identity:
    reinitializeData: false
    postgreSql:
      uri: "jdbc:postgresql://HOST:5432/DB_NAME"
      username: "USER_NAME"
      password: "PASSWORD"
    mail:
      host: HOST
      address: "USER@DOMAIN.COM"
      port: 587
      method: plain
      plainAuthentication:
        username: USER_NAME
        password: PASSWORD
  reading:
    reinitializeData: false
    postgreSql:
      uri: "jdbc:postgresql://HOST:5432/DB_NAME"
      username: "USER_NAME"
      password: "PASSWORD"
    mongoDb:
      uri: "mongodb://HOST/DB_NAME"
  paragraphGenerator:
    openAI:
      url: "https://api.openai.com/v1/chat/completions"
      apiKey: "sk-xxxxxxxx"