core:
  identity:
    reinitializeData: false
    postgreSql:
      uri: "jdbc:postgresql://localhost:5432/ctxwl"
      username: "ctxwl"
      password: "ctxwl"
    mail:
      host: smtp-mail.outlook.com
      address: "vones3@outlook.com"
      port: 587
      method: plain
      plainAuthentication:
        username: vones3@outlook.com
        password: nussyD-zixmup-vaxva7
  reading:
    reinitializeData: false
    postgreSql:
      uri: "jdbc:postgresql://localhost:5432/ctxwl"
      username: "ctxwl"
      password: "ctxwl"
    mongoDb:
      uri: "mongodb://localhost:27017/ctxwl"